In [1]:
import pandas as pd
import numpy as np
import ydata_profiling as yp

In [2]:
housing_data = pd.read_csv('Housing.csv')

In [3]:
housing_data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [4]:
features = housing_data.columns.to_list()

In [5]:
features

['price',
 'area',
 'bedrooms',
 'bathrooms',
 'stories',
 'mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'parking',
 'prefarea',
 'furnishingstatus']

In [6]:
report = yp.ProfileReport(housing_data)

In [7]:
report

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
housing_data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [9]:
#housing_data['mainroad'] = housing_data['mainroad'].apply(lambda x:1 if x == "yes" else 0)

In [10]:
#housing_data['guestroom'] = housing_data['guestroom'].apply(lambda x:1 if x == "yes" else 0)

In [11]:
#housing_data['basement'] = housing_data['basement'].apply(lambda x:1 if x == "yes" else 0)

In [12]:
housing_data[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']] = housing_data[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']].applymap(lambda x:1 if x == "yes" else 0)

In [13]:
housing_data

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

    furnishingstatus  
0          furnished  
1          furnished  
2     semi-furnished  
3          furnished  
4          furnished  
..               ...  
540      unfurnished  
541   semi-furnished  
542      unfurnished  
543        furnished  
544      unfurnished  

[545 rows x 13 columns]

In [14]:
def mapp_furnisher_status(x):
    if x == "unfurnished":
        return 1
    elif x == "semi-furnished":
        return 2
    elif x == "furnished":
        return 3
    else:
        return x

In [15]:
housing_data['furnishingstatus'] = housing_data['furnishingstatus'].apply(mapp_furnisher_status)

In [16]:
housing_data

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   3  
1                   3  
2                   2  
3                   3  
4                   3  
..                ...  
540                 1  
541                 2  
542                 1  
543                 3  
544                 1  

[545 rows x 13 columns]

In [17]:
Y = housing_data['price']

In [18]:
X = housing_data.iloc[:,1:]

In [19]:
from sklearn.linear_model import LinearRegression as lr

In [20]:
model = lr()

In [23]:
model = model.fit(X,Y)

In [27]:
model.coef_

array([2.43906887e+02, 1.19474386e+05, 9.88888287e+05, 4.50391518e+05,
       4.23100741e+05, 2.98030507e+05, 3.57926360e+05, 8.72936027e+05,
       8.53633595e+05, 2.79785637e+05, 6.47055599e+05, 2.13187781e+05])

In [28]:
model.intercept_

-537696.8313211091

In [76]:
X_arr = X.to_numpy()

In [77]:
Y_arr = Y.to_numpy()

In [80]:
X_arr.shape, Y_arr.shape

((545, 12), (545,))

In [81]:
X_arr = X_arr.reshape([12,545])

In [82]:
X_arr.shape

(12, 545)

In [84]:
Y_arr = Y_arr.reshape([1,545])

In [85]:
Y_arr.shape

(1, 545)

In [101]:
W = np.random.randn(12,)

In [104]:
W = W.reshape([12,1])
W.shape

(12, 1)

In [95]:
W

array([[ 0.53524532,  1.21486543, -0.94954774, -0.93570739, -1.05045113,
         0.24782895,  1.35250608, -0.13741764,  0.6323983 ,  1.57156975,
         0.77839948,  0.78707755]])

In [97]:
b = np.random.randn(1)

In [99]:
b.shape

(1,)

In [106]:
Y_pred = np.dot(W.T,X_arr) + b

In [110]:
Y_pred.shape,Y_arr.shape

((1, 545), (1, 545))

In [114]:
X_arr.shape

(12, 545)

In [113]:
initial_loss = np.sum(np.square((Y_pred-Y_arr)))/(2*Y_pred.shape[1])

In [117]:
# 1/m * Sigma(0,m) (y_pred-y)*x
dW = (np.dot(X_arr,(Y_pred-Y_arr).T))/Y_pred.shape[1]

In [118]:
dW

array([[-3.06210756e+09],
       [-2.69605839e+09],
       [-2.60767451e+09],
       [-2.33741744e+09],
       [-2.31294732e+09],
       [-1.81723912e+09],
       [-1.89357633e+09],
       [-1.76005239e+09],
       [-1.65710597e+09],
       [-1.48868122e+09],
       [-1.60124033e+09],
       [-1.34409443e+09]])

In [122]:
# 1/m * Sigma(0,m) (y_pred-y)
db = np.sum(Y_pred-Y_arr)/Y_pred.shape[1]

In [123]:
db

-4765258.803002552

In [124]:
W = W - (10)*dW
b = b - (10)*db

In [125]:
Y_pred = np.dot(W.T,X_arr)+b

In [126]:
second_loss = np.sum(np.square((Y_pred-Y_arr)))/(2*Y_pred.shape[1])

In [127]:
second_loss

8.584907246720022e+27

In [128]:
initial_loss - second_loss

-8.584907246720009e+27